import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import Providers from '../redux/Provider'
import { AuthProvider } from './lib/providers'

export const metadata = {
  title: 'BBTS',
  description: 'Generated by Next.js',
  icons: {
    icon: '/BancoDoBrasil-Logo.svg',
  },
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en" className={`${inter.className} overflow-hidden`}>
        <body className='bg-white text-black'>
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    </AuthProvider>
  )
}
