# Generated by Django 5.1.1 on 2024-10-28 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdTime", models.DateTimeField(verbose_name="Data de Criação")),
                (
                    "lastModifiedTime",
                    models.DateTimeField(verbose_name="Última Modificação"),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Status atual do ticket (e.g., aberto, fechado).",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        help_text="Nível de gravidade do ticket (e.g., baixo, médio, alto).",
                        max_length=20,
                        verbose_name="Gravidade",
                    ),
                ),
                (
                    "assignedTo",
                    models.CharField(
                        help_text="Nome da pessoa ou equipe responsável pelo ticket.",
                        max_length=80,
                        verbose_name="Atribuído a",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título breve do ticket.",
                        max_length=80,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Descrição detalhada do ticket.",
                        max_length=255,
                        verbose_name="Descrição",
                    ),
                ),
            ],
        ),
    ]
