# Generated by Django 5.1.1 on 2024-10-29 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickets",
            name="createdTime",
            field=models.DateField(verbose_name="Data de Criação"),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="lastModifiedTime",
            field=models.DateField(verbose_name="Última Modificação"),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
