# Generated by Django 5.1.1 on 2024-10-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_tickets_createdtime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="incidentURL",
            field=models.CharField(
                default="",
                help_text="URL que direciona ao serviço.",
                max_length=300,
                verbose_name="Link URL do Incidente",
            ),
        ),
        migrations.AddField(
            model_name="tickets",
            name="providerName",
            field=models.CharField(
                default="",
                help_text="Serviço do Incidente.",
                max_length=80,
                verbose_name="Nome do Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="createdTime",
            field=models.DateTimeField(verbose_name="Data de Criação"),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="description",
            field=models.CharField(
                help_text="Descrição detalhada do ticket.",
                max_length=300,
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="lastModifiedTime",
            field=models.DateTimeField(verbose_name="Última Modificação"),
        ),
    ]
