# Generated by Django 5.1.1 on 2024-11-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_tickets_incidenturl_tickets_providername_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="Email do usuário",
                max_length=80,
                null=True,
                verbose_name="Email",
            ),
        ),
    ]
