# Generated by Django 5.1.1 on 2024-11-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_tickets_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickets",
            name="email",
            field=models.CharField(
                help_text="Email do usuário",
                max_length=80,
                null=True,
                verbose_name="Email",
            ),
        ),
    ]
